### PR TITLE
updating pylint rules to match pylint 1.8.3

### PR DESCRIPTION
**Pull request by clarkgaybel**
sonar-python plugin is only aware of pylint rules up to 1.2.1 which is already 4 years old.
This Pull request intend to catch-up up to version 1.8.3, supporting ~100 more rules.
This PR is necessary to keep the pylint integration meaningful.

### CODE REVIEW

**Comment by clarkgaybel** [comment]
This PR is a proactive effort to answer my own question https://groups.google.com/forum/#!topic/sonarqube/ezXW03MzzYU

**Comment by clarkgaybel** [comment]
@pynicolas can you please review this PR?

**Comment by pynicolas** [comment]
Thanks a lot for the PR! Indeed, updating the list of pylint rules should be done more often.

I have 2 remarks about the content of the PR:
- Rules should not be deleted (e.g. C0322): users relying on an old version of pylint should still be able to have their issues imported.
- Preserving the existing indentation of `rules.xml` would make it much easier to review the changes (we don't care much about `rules_generated.xml`).

I'll try to handle those 2 points at the end of next week if nobody has done it before.

Thanks again!

**Comment by clarkgaybel** [comment]
Thanks @pynicolas, that will be much appreciated here. Let me know if you can't make it and I'll give it a try even though I'm no expert at all in merging XMLs.

Thanks.

**Comment by pynicolas** [comment]
@clarkgaybel I opened PR #149 based on what you did. Please have a look at it and test it.

**Comment by pynicolas** [comment]
This PR was replaced by #149 which was heavily based on this one. Thanks!

**Comment by pynicolas** [comment]
@tquenolle @AubryH This change should be released as part of SonarPython 1.10. Please see the [request for feedback](https://groups.google.com/d/msg/sonarqube/5uqpdy40Z-Q/fxTtOGTbAQAJ). Thanks!

**Pull request closed without merging**
