### PR TITLE
SONARPY-684 Count module-level docstrings as comments

### PR DESCRIPTION
**Pull request by guillaume-dequenne-sonarsource**
Duplicates #707 to trigger all checks.

### CODE REVIEW

**Comment by hugobuddel** [comment]
Thank you for looking into this @guillaume-dequenne-sonarsource 

By the way, I tried to get this line to have full coverage:
```
} else if (!isBlank(commentLine) && !noSonar.contains(line)) {
```
but I failed. It seems that `!noSonar.contains(line)` is always true. And I can't see how it can be otherwise, because the line is added to noSonar in the other part of the if clause.

**Comment by guillaume-dequenne-sonarsource** [comment]
You're right, I don't think `!noSonar.contains(line)` could ever be false there. 

I also think it is not be possible for the `commentLines` array to contain more than one element (since there are no true multi-line comments in Python), so I could simplify the `visitComment` method quite a bit in 1e735e42c4fcbcc080e5e4a4f732aba4b94776d0.  Can you do a quick review of that @andrea-guarino-sonarsource ?

**Comment by andrea-guarino-sonarsource** [comment]
@guillaume-dequenne-sonarsource LGTM for 1e735e4

**Comment by hugobuddel** [comment]
Thanks for the quick response @guillaume-dequenne-sonarsource and @andrea-guarino-sonarsource! This cuts my issue count in half ✂️.

**Pull request merged**
