### PR TITLE
start multiple pylint processes

### PR DESCRIPTION
**Pull request by roivanov**
It takes about 20 minutes to run sonar-python sequentially on a project with ~500 python files.
By running with 10 java threads (and pylint processes) run time went down to 3 minutes.

### CODE REVIEW

**Comment by vilchik-elena** [comment]
@roivanov If you run pylint outside of the SonarPython on the same project does it take the same long?

**Comment by roivanov** [comment]
Running pylint outside of SonarPython takes ~3 minutes. The difference between running pylint alone is that I can specify number of jobs (-j 10) in pylintrc file or as command line argument. Also, pylint takes whole project directory not every single file per each run.

**Comment by roivanov** [comment]
Pull request updated to the new plugin code

**Comment by saberduck** [comment]
See #105  and https://jira.sonarsource.com/browse/SONARPY-328

**Pull request closed without merging**
