### PR TITLE
S125: Ignore encoding header according to PEP 263

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by andrea-guarino-sonarsource** [comment]
Hi @diorcety , thank you for your contribution. I created ticket [here](https://jira.sonarsource.com/browse/SONARPY-465) to keep track of this false positive.
I will open a new PR, keeping your commit, to enable our full integration test pipeline.

**Comment by diorcety** [comment]
Thanks. I tried to create a ticket on your issue tracker but I didn't have the rights.

**Comment by andrea-guarino-sonarsource** [comment]
Closing this PR, because PR https://github.com/SonarSource/sonar-python/pull/439 has been merged. Thank you again!

**Comment by diorcety** [comment]
Thanks

**Pull request closed without merging**
